version: '3'
services:
  build:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes: 
      - ..:/app
    working_dir: /app
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      COMMUNITY_SHEET_ID: ${COMMUNITY_SHEET_ID}
      OUTPUT_PATH: /app/Web/wwwroot/api/data.json
    command: ./tasks/build.sh
  deploy:
    build:
      context: .
      dockerfile: deploy.Dockerfile
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      NOTIFICATION_EMAIL: ${NOTIFICATION_EMAIL}
      CFN_STACK_NAME: ${CFN_STACK_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    command: ./tasks/deploy.sh
