name: pipeline
on:
  push:
    branches:
      - master
jobs:
  pipeline:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker-compose -f tasks/docker-compose.yml build build
          docker-compose -f tasks/docker-compose.yml run build
          docker-compose -f tasks/docker-compose.yml down
      - name: deploy_development
        env:
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
          CFN_STACK_NAME: Development
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          docker-compose -f tasks/docker-compose.yml build deploy
          docker-compose -f tasks/docker-compose.yml run deploy
          docker-compose -f tasks/docker-compose.yml down 
      - name: cleanup
        if: always()
        run: |
          docker-compose -f tasks/docker-compose.yml down --volumes --remove-orphans
          docker system prune --force
