name: pipeline
on:
  push:
    branches:
      - master
jobs:
  pipeline:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker-compose -f tasks/docker-compose.yml build build
          docker-compose -f tasks/docker-compose.yml run build
          docker-compose -f tasks/docker-compose.yml down
      - name: cleanup
        if: always()
        run: |
          docker-compose -f tasks/docker-compose.yml down --volumes --remove-orphans
          docker system prune --force
  